[package]
name = "Sentient-Core"
version = "0.1.0"
edition = "2021"
description = "Sample Horizon plugin demonstrating core functionality"
license = "MIT"
repository = "https://github.com/Far-Beyond-Dev/your-plugin"

[lib]

[dependencies]
